# config.yaml
GD_settings:     
  lossparameter: "cl"                           #which quality parameter to use as loss (see fitspectra-HeP.py for description)
                                                # hyperparameters of the gradient descent algorithm
  n_closest_points: "Global"                    # how many closest points are taken into account for fitting the ridge model: for all set "Global", otherwise int
  scaler: "Standard"                              #options: "Standard" or Robust
  start_point: "Best"                           #options: "Best" or "Random" or "Farthest" or "FarGood"
  weighting: "Exponential"                             # Weighting of closest point during fit: "Exponential" (exp(-loss)) or "Distance" ((1+1/d)^dwp) or "None" (all have same weight)               
  dist_weight_power: 0                          # parameter dwp for "Distance" weigth option
  infliketreatment: "remove"                                    #"replace"
  maxloss: "maxval"                             #"maxval" for maximum value of loss in of points, or integer

  model_type: "Polynomial"                      #"Polynomial" or "Spline"
  force_center: true                            # shift data so that startpoint for gradient descent is at position 0 with loss 0 (does not work with "Spline"?)  
  fit_mode: "Auto"                              # "Auto" or "Manual" for tuning of fit hyperparameters (degree, alpha), if "Manual" use values below max_poly_degree:
  max_degree: 3                                 #also degree for Spline
  max_knots: 6                                  # only for Spline
  degree: 2                                     # Degree of fitted ridge model (if manual mode, otherwise replaced by result of hyperparameter opt.)
  alpha: 0.14                                   # Regularization of ridge model (good values from "manual" test were Local 250: deg=2, alpha=0.14, Global: deg=2, alpha=0.09)
  knots: 4                                      # Knots of fitted ridge spline model (if manual mode, otherwise replaced by result of hyperparameter opt.)
                
  momentum_type: "Normal"                         # How to calculate next gradient step with momentum: "Nesterov", "Auto" or "Normal"
  momentum_decay: 0.0                           # How much of previous momentum is kept in each step (1.0: all momentum is kept, 0.0: no momentum is kept and only gradient decides step)
  learning_rate: 0.001                         # Step size of gradient  (if momentum type is "Auto" this is used as the upper limit)
  gradient_calc: "Numeric"                      # "Numeric" or "Analytic" (must be numeric for spline!)
  
  useinterpoldata: false
  useinterpolbest: false
  interpoldataweight: 0.01
  
preset_parameters:                              # Used for setting parameter values which are not supposed to be part of optimisation (if none, leave empty)
  highexp: 0.0001
  
comp_settings:                                  # computational settings
  simulation_IP: 45                           # which computer to run simulations on
  load_previous: false                          # load most recent data with same runsettings or take current best point instead
  max_gradient_steps: 20                         # How many steps to calculate (set null if unlimited)
  autorestart: true

paths:                                        # paths to files/folders used by the script
  progress_dir: "/home/motz/CALETana/prop/GradientDescent/DescentData"                # directory of previous progress safe folders

  #fitSpectra_path: "/home/motz/CALETana/astro/fitspectra-HeP.py"                           # path to fitspectra-xxx.py
  #fitSpectra_path: "/home/motz/CALETana/astro/fitspectra-HeP-NB.py"                           # path to fitspectra-xxx.py
  fitSpectra_path: "/home/motz/CALETana/astro/fitspectra-HeP-conv.py"                           # path to fitspectra-xxx.py
  #dragondata_path: "/home/motz/CALETana/astro/CALplots/fitspectra-HeP_fitsave-5.0.dat"     # path to dragon simulation data in "fitspectra-xxx-5.0.dat"
  #dragondata_path: "/home/motz/CALETana/astro/CALplots/fitspectra-HeP-NB_fitsave-5.0.dat"     # path to dragon simulation data in "fitspectra-xxx-5.0.dat"
  dragondata_path: "/home/motz/CALETana/astro/CALplots/fitspectra-HeP-conv_fitsave-5.0.dat"     # path to dragon simulation data in "fitspectra-xxx-5.0.dat"
  #interpoldata_path: "/home/motz/CALETana/astro/CALplots/fitspectra-HeP_interpolmap-5.0.dat"     # path to dragon simulation data in "fitspectra-xxx-5.0.dat"
  interpoldata_path: "/home/motz/CALETana/astro/CALplots/fitspectra-HeP-conv_interpolmap-5.0.dat"     # path to dragon simulation data in "fitspectra-xxx-5.0.dat"
  #interpoldata_path: "/home/motz/CALETana/astro/CALplots/fitspectra-HeP-NB_interpolmap-5.0.dat"     # path to dragon simulation data in "fitspectra-xxx-5.0.dat"
  dragonbkg_path: "/home/motz/dragon_calet/dragonbkgauto.py"                                   # path to dragonbkg.py
  
  # fitSpectra_path: "/home/ehanser/CALETana/astro/fitspectra-SiP.py"                            
  # dragondata_path: "/home/ehanser/CALETana/astro/CALplots/fitspectra-SiP_fitsaveCAL_NV_Be_CHe-5.0.dat"
  # dragonbkg_path: "/home/ehanser/dragon_calet/dragonbkg_Si.py"
